### ISSUE TITLE
No module named 'gridding'

### ISSUE THREAD

**Issue by katsunori-waragai** [pairlab/TranspareNet#5]
Thank you for your implementation of TranspareNet.
I found it very interesting as a library to improve the depth from RGB and raw Depth images, including transparent objects.
I would like to port it to Jetson AGX Orin and make it work.
So I built the environment.
However, as the module for gridding has not been created
I could not run inference_transparenet.py.
How can I create the gridding module?

# Environment
Jetson AGX Orin

Ubuntu 20.04 LTS
JetPack5.1,
L4T 35.2.1
CuDNN 8.6.0,
CUDA 11.4.19,
TensorRT 8.5.2,

## Docker environment
python3 -m pip install -r requierments.txt

## Error
```
python3 inference_transparenet.py 
Traceback (most recent call last):
  File "inference_transparenet.py", line 4, in <module>
    from grnet_point_cloud_completion.models.grnet import GRNet
  File "/root/TranspareNet/grnet_point_cloud_completion/models/grnet.py", line 10, in <module>
    from grnet_point_cloud_completion.extensions.gridding import Gridding, GriddingReverse
  File "/root/TranspareNet/grnet_point_cloud_completion/extensions/gridding/__init__.py", line 10, in <module>
    import gridding
ModuleNotFoundError: No module named 'gridding'
```
## My understanding of the problem situation
I assume that the cu files and cpp files in the following locations are not compiled and not bound to python3, which is causing the problem.
```
find . -name "gridding*" -print
./grnet_point_cloud_completion/extensions/gridding_loss
./grnet_point_cloud_completion/extensions/gridding_loss/gridding_distance.cu
./grnet_point_cloud_completion/extensions/gridding_loss/gridding_distance_cuda.cpp
./grnet_point_cloud_completion/extensions/gridding
./grnet_point_cloud_completion/extensions/gridding/gridding_cuda.cpp
./grnet_point_cloud_completion/extensions/gridding/gridding.cu
./grnet_point_cloud_completion/extensions/gridding/gridding_reverse.cu
```

## Expected response
I would like to see a way of binding to python3 using cu files, cpp files.

**Comment by katsunori-waragai** [comment]
All I have to do is to execute as follows.
```
  cd /root/TranspareNet/grnet_point_cloud_completion/extensions/gridding
  python3 setup.py install
  cd /root/TranspareNet/grnet_point_cloud_completion/extensions/gridding_loss/
  python3 setup.py install
  cd /root/TranspareNet//grnet_point_cloud_completion/extensions/cubic_feature_sampling/
  python3 setup.py install
  cd /root/TranspareNet/grnet_point_cloud_completion/extensions/chamfer_dist/
  python3 setup.py install
```

**Comment by katsunori-waragai** [comment]
resolved
